/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Authentication {
  kerberosTicket?: string;
  password?: string;
  realm?: string;
  username?: string;
}
